safe: false
#markdown: kramdown
#highlighter: rouge
permalink: /posts/:title.html
exclude:
  - README.md

name: StillNoon
host: stillnoon.com
desc: Time is running out.

custom:
    category:
        think: Think
        redaing: Reading
        exception: MyException
        tools: Tools
        python: Python
        about: About
    categories:
      - name:  think
        title: Think

      - name:  reading
        title: Reading

      - name:  exception
        title: MyException

      - name:  tools
        title: Tools

      - name:  python
        title: Python

      - name:  about
        title: About
    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: hehedanli
        email: hehedanli@foxmail.com
        disqus: stillnoon               # Disqus缩略标识
        gcse: 014273410759249336696:p_rn5xps1vq     # Google自定义搜索标识ID
        github: hehedanli                 # GitHub账号
        #gravatar:   #Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    #gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
